version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${SQLSERVER_SA_PASSWORD:-yourStrong(!)Password}
    volumes:
    - mssql-server19-linux-data:/var/opt/mssql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mssql-server19-linux-data: